# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcolumns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columncollection',
            name='dynamic_column',
            field=models.ManyToManyField(related_name='column_collection', to='dcolumns.DynamicColumn', verbose_name='Dynamic Columns'),
        ),
    ]
