# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-09 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcolumns', '0002_auto_20160130_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyvalue',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyvalues', to='dcolumns.CollectionBase', verbose_name='Collection Type'),
        ),
        migrations.AlterField(
            model_name='keyvalue',
            name='dynamic_column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyvalues', to='dcolumns.DynamicColumn', verbose_name='Dynamic Column'),
        ),
    ]
