# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcolumns', '0004_columncollection_related_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamiccolumn',
            name='location',
            field=models.CharField(choices=[('author_top', 'author-top'), ('author_center', 'author-center'), ('author_bottom', 'author-botton'), ('book_top', 'book-top'), ('book_center', 'book-center'), ('book_bottom', 'book-bottom'), ('promotion_top', 'promotion-top'), ('promotion_center', 'promotion-center'), ('promotion_bottom', 'promotion-bottom'), ('publisher_top', 'publisher-top'), ('publisher_center', 'publisher-center'), ('publisher_bottom', 'publisher-bottom')], help_text='Choose a display location.', max_length=50, verbose_name='Display Location'),
        ),
        migrations.AlterField(
            model_name='dynamiccolumn',
            name='order',
            field=models.PositiveSmallIntegerField(verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='dynamiccolumn',
            name='value_type',
            field=models.IntegerField(choices=[(1, 'Boolean'), (2, 'Choice'), (3, 'Date'), (4, 'Date Time'), (5, 'Floating Point'), (6, 'Number'), (7, 'Text'), (8, 'Text Block'), (9, 'Time')], help_text='Choose the value type.', verbose_name='Value Type'),
        ),
    ]
