# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcolumns', '0005_auto_20160906_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamiccolumn',
            name='location',
            field=models.CharField(help_text='Choose a display location.', max_length=50, verbose_name='Display Location'),
        ),
    ]
