# Generated by Django 3.2.3 on 2021-05-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcolumns', '0006_auto_20160906_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionbase',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='columncollection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dynamiccolumn',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='keyvalue',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
