# Generated by Django 4.2.2 on 2023-06-16 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dcolumns', '0007_auto_20210518_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionbase',
            name='creator',
            field=models.ForeignKey(editable=False, help_text='The user who created this record.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creator_related', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='collectionbase',
            name='updater',
            field=models.ForeignKey(editable=False, help_text='The last user to update this record.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updater_related', to=settings.AUTH_USER_MODEL, verbose_name='Updater'),
        ),
        migrations.AlterField(
            model_name='columncollection',
            name='creator',
            field=models.ForeignKey(editable=False, help_text='The user who created this record.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creator_related', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='columncollection',
            name='updater',
            field=models.ForeignKey(editable=False, help_text='The last user to update this record.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updater_related', to=settings.AUTH_USER_MODEL, verbose_name='Updater'),
        ),
        migrations.AlterField(
            model_name='dynamiccolumn',
            name='creator',
            field=models.ForeignKey(editable=False, help_text='The user who created this record.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creator_related', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='dynamiccolumn',
            name='updater',
            field=models.ForeignKey(editable=False, help_text='The last user to update this record.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updater_related', to=settings.AUTH_USER_MODEL, verbose_name='Updater'),
        ),
    ]
